apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-px78
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-px78
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-px78
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-px78
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-px78
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-jqft-tenant/dotnet-component/devfile-sample-dotnet60-basic-px78@sha256:f5f279f5fadc4e4af810c26e196c70c4b85f38bab81b1e3c0b18abe4825d1d2a
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
